apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: pv-obs-example 
  annotations:
    pv.kubernetes.io/provisioned-by: flexvolume-huawei.com/fuxiobs
spec: 
  accessModes: 
  - ReadWriteMany 
  capacity: 
    storage: 1Gi 
  flexVolume: 
    driver: huawei.com/fuxiobs 
    fsType: obs 
    options: 
      fsType: obs 
      region: eu-west-0
      storage_class: STANDARD 
      volumeID: obs-dafu 
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: obs-standard
