apiVersion: v1
kind: Service
metadata:
  name: svc-test-elb
  labels:
    app: nginx-test
  annotations:
    service.protal.kubernetes.io/type: LoadBalancer
    kubernetes.io/elb.class: union
    kubernetes.io/elb.subnet-id: d6b9ae12-debd-48dc-8d05-44760d5ebf1f
    kubernetes.io/elb.autocreate: >-
      {"type":"public","bandwidth_name":"cce-bandwidth-test-elb","bandwidth_chargemode":"traffic","bandwidth_size":5,"bandwidth_sharetype":"PER","eip_type":"5_bgp"}
spec:
  selector:
    app: nginx-test
  ports:
    - name: cce-service-0
      targetPort: 80
      nodePort: 0
      port: 80
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: ''
